<?php
/*
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC. All rights reserved.                        |
 |                                                                    |
 | This work is published under the GNU AGPLv3 license with some      |
 | permitted exceptions and without any warranty. For full license    |
 | and copyright information, see https://civicrm.org/licensing       |
 +--------------------------------------------------------------------+
 */

 use CRM_Fpptareports_ExtensionUtil as E;

/**
 *
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 */
class CRM_Fpptareports_Form_Report_Member_FPPTAMemberStartEnd extends CRM_Report_Form {

  const MEMBERSHIP_STATUS_ACTIVITY_TYPE_ID = 35;
  const MEMBERSHIP_SIGNUP_ACTIVITY_TYPE_ID = 7;
  const MEMBERSHIP_RENEWAL_ACTIVITY_TYPE_ID = 8;
  const MEMBERSHIP_TYPE_IDS_IN = '1, 2';

  protected $yearFilterLabel = "";
  
  protected $_customGroupExtends = [
    'Member',
    'Contact',
    'Individual',
  ];

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->_columns = [
      'civicrm_contact' => [
        'dao' => 'CRM_Contact_DAO_Contact',
        'fields' => array_merge([
          // CRM-17115 - to avoid changing report output at this stage re-instate
          // old field name for sort name
          'sort_name_linked' => [
            'title' => E::ts('Member Name'),
            'required' => TRUE,
            'no_repeat' => TRUE,
            'dbAlias' => 'contact_civireport.sort_name',
          ],
          'id' => [
            'required' => TRUE,
            'no_display' => TRUE,
          ],
        ],
        ),
        'grouping' => 'contact-fields',
        'order_bys' => [
          'sort_name' => [
            'title' => E::ts('Last Name, First Name'),
            'default' => '1',
            'default_weight' => '0',
            'default_order' => 'ASC',
          ],
        ],
      ],
      'civicrm_membership' => [
        'fields' => [
          'join_date' => [
            'title' => E::ts('Member Since'),
            'default' => TRUE,
          ],
          'start_date' => [
            'title' => E::ts('Membership Start Date'),
            'default' => TRUE,
          ],
          'end_date' => [
            'title' => E::ts('Membership End Date'),
            'default' => TRUE,
          ],
          'membership_type_id' => [
            'title' => E::ts('Membership Type'),
            'default' => TRUE,
          ],
        ],
        'grouping' => 'membership-fields',
        'filters' => [
          'year' => [
            'pseudofield' => TRUE,
            'operatorType' => CRM_Report_Form::OP_SELECT,
            'options' => $this->_yearOptions(),
            'type' => CRM_Utils_Type::T_INT,
            'title' => $this->yearFilterLabel,
          ],
        ],
      ],
      'civicrm_activity' => [
        'fields' => [
          'activity_type_id' => [
            'title' => E::ts('Activity Type'),
            'default' => TRUE,
          ],
          'subject' => [
            'title' => E::ts('Activity Subject'),
            'default' => TRUE,
          ],
          'activity_date_time' => [
            'title' => E::ts('Activity Date/Time'),
            'default' => TRUE,
          ],
        ],
        'grouping' => 'activity-fields',
      ],
    ];

    parent::__construct();
  }

  public function from() {
    $this->_from = "
        FROM civicrm_contact {$this->_aliases['civicrm_contact']}
          INNER JOIN (" . $this->_generateTempTableQuery() . ") t on t.contact_id = {$this->_aliases['civicrm_contact']}.id
             {$this->_aclFrom}
      ";
    if ($this->isTableSelected('civicrm_membership')) {
      $this->_from .= "
        INNER JOIN civicrm_membership {$this->_aliases['civicrm_membership']}
          ON {$this->_aliases['civicrm_membership']}.id = t.membership_id
      ";
    }
    if ($this->isTableSelected('civicrm_activity')) {
      $this->_from .= "
        INNER JOIN civicrm_activity {$this->_aliases['civicrm_activity']}
          ON {$this->_aliases['civicrm_activity']}.id = t.activity_id
      ";
    }

    $this->joinAddressFromContact();
    $this->joinPhoneFromContact();
    $this->joinEmailFromContact();

  }

  /**
   * Alter display of rows.
   *
   * Iterate through the rows retrieved via SQL and make changes for display purposes,
   * such as rendering contacts as links.
   *
   * @param array $rows
   *   Rows generated by SQL, with an array for each row.
   */
  public function alterDisplay(&$rows) {
    $entryFound = FALSE;
    $activityTypes = CRM_Activity_BAO_Activity::buildOptions('activity_type_id');
    $membershipTypes = CRM_Member_BAO_Membership::buildOptions('membership_type_id');
    foreach ($rows as $rowNum => $row) {
      // Convert display name to link
      $displayName = CRM_Utils_Array::value('civicrm_contact_sort_name_linked', $row);
      $cid = CRM_Utils_Array::value('civicrm_contact_id', $row);
      if ($displayName && $cid) {
        $url = CRM_Utils_System::url('civicrm/contact/view',
          "reset=1&cid=$cid"
        );

        $contactTitle = E::ts('View Contact Record');

        $rows[$rowNum]['civicrm_contact_sort_name_linked'] = "<a title='$contactTitle' href=$url>$displayName</a>";
        $entryFound = TRUE;
      }

      if (array_key_exists('civicrm_activity_activity_type_id', $row)) {
        $rows[$rowNum]['civicrm_activity_activity_type_id'] = $activityTypes[$rows[$rowNum]['civicrm_activity_activity_type_id']];
        $entryFound = TRUE;
      }

      if (array_key_exists('civicrm_membership_membership_type_id', $row)) {
        $rows[$rowNum]['civicrm_membership_membership_type_id'] = $membershipTypes[$rows[$rowNum]['civicrm_membership_membership_type_id']];
        $entryFound = TRUE;
      }
      // skip looking further in rows, if first row itself doesn't
      // have the column we need
      if (!$entryFound) {
        break;
      }
    }
  }

  private function _yearOptions() {
    $ret = [];
    $i = 2019;
    $currentYear = (int) date("Y");
    while ($i <= $currentYear) {
      $ret[$i] = $i;
      $i++;
    }
    return $ret;
  }
}
